project:
  type: website
  output-dir: docs

website:
  title: "Cryptocurrency Spike Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - volume.qmd
      - about.qmd
      - sources.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



